### ISSUE TITLE
[1.15pre] fisticuffs with nbtcrafting, act 3

### ISSUE THREAD

**Issue by Yoghurt4C** [CottonMC/LibCD#11]
https://github.com/Siphalor/nbt-crafting/issues/26

**Comment by Boundarybreaker** [comment]
I'll take a whack at this again sometime soon. If I recall correctly, the last time I tried to reproduce this I couldn't, so I'll see if it pops its head up.

**Comment by Boundarybreaker** [comment]
I haven't been able to reproduce this and I haven't heard anyone else complain about it yet, so I'm gonna close this and then if it happens again it can be re-opened.
