### ISSUE TITLE
Crash to Desktop Clientside on new version

### ISSUE THREAD

**Issue by AltimusX** [CottonMC/LibCD#16]
The previous version works but the update crashes my client before the app window opens.

https://pastebin.com/t9bWQHsh
Also happens on 1.15.2 pre2 <- all future tests will be committed from this branch until rc1.15.2 goes live.

All necessary data is in the pastebin link.

**Comment by Boundarybreaker** [comment]
Yep, this is known and I've been whacking at it for a little while. This is due to some *really* annoying class access rules in vanilla based around how cooking and cutting recipes are built. I'll hopefully have a better solution soon.

**Comment by Boundarybreaker** [comment]
A temp fix has been applied in 2.2.1.
