### ISSUE TITLE
releases conditionals broken, built from source work

### ISSUE THREAD

**Issue by MechanicalDragon0687** [CottonMC/LibCD#18]
**Describe the bug**
using current release of libcd (2.2.2) and previous version 2.2.1
on load of world, sample tweaker scripts are run
if built on my own machine from source (clone, then run gradle build), sample scripts are not run.

likely something is wrong with the build environment for releases at the moment. 

**Version of the (please complete the following information):**
 - Mod: 2.2.2 or 2.2.1
 - Fabric API: current
 - Minecraft: 1.15.2
 - REI also loaded to easily check recipes

**released 2.2.2 and 2.2.1 causes errors:**
when launching to title:
`[23:41:04] [main/WARN]: Reference map 'libcd-refmap.json' for mixins.libcd.json could not be read. If this is a development environment you can ignore this message`

and when loading world:
`[23:41:51] [ForkJoinPool.commonPool-worker-1/INFO]: [LibCD|libcd:tweaker_test.js] WARNING! LibCD Tweaker sample script is running!
[23:41:51] [ForkJoinPool.commonPool-worker-1/INFO]: [LibCD|libcd:tweaker_test.js] If you are not in a dev environment, please report this!
[23:41:51] [ForkJoinPool.commonPool-worker-1/INFO]: [LibCD] Applied 2 tweaker scripts, including 36 recipes (6 removed) and 1 modified loot table`

built 2.2.2 shows no message

**Comment by Boundarybreaker** [comment]
oh boy, apparently loom *didn't* update after all. Time to workaround.

**Comment by Boundarybreaker** [comment]
Okay, it very much looks like there's some major fuckery going on beyond just this issue. I'm pulling version 2.2.2 temporarily so I can figure out what the hell is going on.

**Comment by MechanicalDragon0687** [comment]
for what it's worth, when i build it as-is, it works

**Comment by Boundarybreaker** [comment]
yes, that's what's so confusing here, it's something with my dev env that's acting haunted for no good reason. I'm trying to figure out what it is so I can actually fix it for future releases.

**Comment by Boundarybreaker** [comment]
Ok, looks like it's *finally* fixed with the new 2.2.2 re-release.
