### ISSUE TITLE
InvalidMixinException in 20w15a

### ISSUE THREAD

**Issue by bluebear94** [CottonMC/LibCD#26]
**Describe the bug**
Using LibCD version 2.3.1+20w15a crashes the game when loading the world with an `InvalidMixinException`.

**To Reproduce**
1. Load a world on 20w15a with LibCD 2.3.1+20w15a is installed

**Expected behavior**
The world loads

**Version of the (please complete the following information):**
 - LibCD 20w15a
 - Fabric API 0.5.9+build.319-1.16
 - Minecraft 20w15a

**Additional context**
Game log: [latest.log](https://github.com/CottonMC/LibCD/files/4467575/latest.log)

This seems to occur because `MixinTagBuilder` shadows a field called `entries` that is assumed to be a `Set<Tag.Entry>`, but the field in `Tag.Builder` is of type `List<Tag.class_5145>`.

**Comment by Boundarybreaker** [comment]
Sounds like a remapping error. I'll talk to @draylar about it.

**Comment by Draylar** [comment]
20w15a adds a new Tag (class_5145) with information (a string) on the resource pack's name. It has a private constructor, and I can't figure out access wideners, so it might be a little bit until a fix.

**Comment by Juuxel** [comment]
Can't you use an invoker mixin for the private constructor?

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/79141840-31063e00-7d80-11ea-9d9a-f27e82e0e4b3.png)
Opening up a PR now.

**Comment by Boundarybreaker** [comment]
@bluebear94 Can we confirm that this is fixed?
