### ISSUE TITLE
New condition: dev mode

### ISSUE THREAD

**Issue by sargunv** [CottonMC/LibCD#28]
Suggested condition: `libcd:dev_mode`, a condition that is met only when running a mod in dev mode, not in prod. This would be useful for testing mods that include some data pack related functionality without risking accidentally publishing the test data with the mod.

If this is something you'd accept, I don't mind writing and PRing it myself.

**Comment by Boundarybreaker** [comment]
This [already exists](https://github.com/CottonMC/LibCD/blob/1.15/src/main/java/io/github/cottonmc/libcd/CDContent.java#L190-L193), it just uses a boolean in LibCD config.

**Comment by sargunv** [comment]
Ah, perfect! I didn't see it in the docs, so I assumed it didn't exist.

**Comment by Boundarybreaker** [comment]
Yeah, docs really need to be updated but I don't have the time.
