### ISSUE TITLE
 Unsupported root entry

### ISSUE THREAD

**Issue by AmibeSkyfy16** [CottonMC/LibCD#37]
**Describe the bug**
I have this warning in the first line of the script when starting server.jar
The mod "libcd" contains invalid entries in its mod json: - Unsupported root entry "licence" at line 9 column 12

**To Reproduce**
Running a server with LibCD mod

**Expected behavior** *Optional*

**Screenshots** *Optional*

**Version of the (please complete the following information):**
 - Mod libcd 3.0.3+1.16.3
 - Fabric API 0.12.5
 - Minecraft 1.17.1

**Additional context** *Optional*

**Comment by LemmaEOF** [comment]
This is already fixed, but I'm retired and am not willing to publish a new version after someone called me slurs and sent me death threats over it.

For anyone checking the issues page and wondering about this, **THIS IS NOT THE CAUSE OF YOUR GAME CRASHING. IT IS NOT A FATAL ERROR. LOOK LATER IN THE LOG.**
