### ISSUE TITLE
Scripts that use RecipeTweaker.makeIngredient don't load on dedicated servers

### ISSUE THREAD

**Issue by MarioAndWeegee3** [CottonMC/LibCD#7]
`makeIngredient` calls `Ingredient.getStackArray`. This method is marked Client-only (I'm not really sure why), and that causes any scripts that use it to fail when loading a dedicated server. I have [this log](https://gist.github.com/WardsParadox/ed59889cb004f0105b53abc057a692b0).

**Comment by Boundarybreaker** [comment]
Oh god, not again.

**Comment by Boundarybreaker** [comment]
Okay, this one is *so much less awful* than `ofStacks` being client-only. I've got a fix in dev and I'm gonna add a few more things to LibCD before I push a new ver.
