### ISSUE TITLE
Debugging lines still in prod jar

### ISSUE THREAD

**Issue by Boundarybreaker** [CottonMC/LibCD#9]
![](https://cdn.discordapp.com/attachments/590253285068242945/635011270244040715/unknown.png)

I apparently forgot to take out some of my debug lines? I swear I removed em. I'll fix it in the morning.

**Comment by Juuxel** [comment]
It's these two:
https://github.com/CottonMC/LibCD/blob/7721e937eaaadfb8786f3f49a0f05b1e49abbe94/src/main/java/io/github/cottonmc/libcd/mixin/MixinResourceManagerImpl.java#L46
https://github.com/CottonMC/LibCD/blob/7721e937eaaadfb8786f3f49a0f05b1e49abbe94/src/main/java/io/github/cottonmc/libcd/mixin/MixinResourceManagerImpl.java#L51
